/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Oracle;

import dbs.oracleConnection;
import query.OracleSysQuery;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.tableHandler;

/**
 *
 * @author kongh
 */
public class Sys extends javax.swing.JPanel {
    oracleConnection conn = new oracleConnection().getInstance();
    OracleSysQuery sys = new OracleSysQuery();
    ResultSet rs = sys.getSGAInf();
    /**
     * Creates new form System
     */
    public Sys() {
        initComponents();
        initial();
    }
    
    public void initial(){
        cb_Target.addItem("SGA");
        cb_Target.addItem("PGA");
        cb_Target.addItem("PROCESS");
        cb_Target.addItem("INSTANCE");
        cb_Target.addItem("DATABASE");
        cb_Target.addItem("DATAFILE");
        cb_Target.addItem("CONTROL FILE");
        cb_Target.addItem("PARAMETER");
        cb_Target.addItem("SPFILE");
        cb_Target.setSelectedIndex(0);
    }
    
    void loadData(ResultSet result){
        try{
            DefaultTableModel model = tableHandler.buildTableModel(result);
            table_System.setModel(model);
        } catch(SQLException | Error err){
            JOptionPane.showMessageDialog(this, "Cannot load data");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Refresh = new javax.swing.JButton();
        cb_Target = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_System = new javax.swing.JTable();

        btn_Refresh.setText("Refresh");

        cb_Target.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TargetActionPerformed(evt);
            }
        });

        table_System.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_System);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_Target, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Refresh)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Target, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb_TargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TargetActionPerformed
        // TODO add your handling code here:
        int index = cb_Target.getSelectedIndex();
        switch(index){
            case 0 -> rs = sys.getSGAInf();
            case 1 -> rs = sys.getPGAInf();
            case 2 -> rs = sys.getProcessInf();
            case 3 -> rs = sys.getInstanceInf();
            case 4 -> rs = sys.getDatabaseInf();
            case 5 -> rs = sys.getDatafileInf();
            case 6 -> rs = sys.getControlFileInf();
            case 7 -> rs = sys.getParameterInf();
            case 8 -> rs = sys.getSPFileInf();
        }
        loadData(rs);
    }//GEN-LAST:event_cb_TargetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Refresh;
    private javax.swing.JComboBox<String> cb_Target;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_System;
    // End of variables declaration//GEN-END:variables
}
