/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Oracle;

import dbs.oracleConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import query.UserQuery;
import utils.tableHandler;
import utils.textFieldHandler;

/**
 *
 * @author kongh
 */
public class User extends javax.swing.JPanel {
    oracleConnection conn = new oracleConnection().getInstance();
    UserQuery profile = new UserQuery();
    ResultSet rs = profile.getAllUsersInfo();
    String usernamePlaceholder = "Username";
    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        initial();
    }
    
    void initial(){
        loadData(rs);
        textFieldHandler.addPlaceHolder(txt_Username, usernamePlaceholder);
    }
    
    void loadData(ResultSet result){
        try{
            DefaultTableModel model = tableHandler.buildTableModel(result);
            table_UserInfo.setModel(model);
        } catch(SQLException err){
            JOptionPane.showMessageDialog(this, "Cannot load data");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Username = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_UserInfo = new javax.swing.JTable();
        btn_Find = new javax.swing.JButton();

        table_UserInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_UserInfo);

        btn_Find.setText("Find");
        btn_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Find)
                        .addGap(0, 223, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Find))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FindActionPerformed
        // TODO add your handling code here:
        String user = txt_Username.getText();
        if(user.compareTo(usernamePlaceholder)==0){
            rs=profile.getAllUsersInfo();
        } else {
            rs=profile.getUserInfo(user);
        }
        loadData(rs);
    }//GEN-LAST:event_btn_FindActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Find;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_UserInfo;
    private javax.swing.JTextField txt_Username;
    // End of variables declaration//GEN-END:variables
}
